# Generated by Django 5.0.6 on 2024-05-19 19:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailygoal',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdailygoal',
            name='daily_quest',
            field=models.ManyToManyField(blank=True, to='core.userdailyquest'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_image_directory_path),
        ),
        migrations.DeleteModel(
            name='GoalCategory',
        ),
    ]
