# Generated by Django 5.0.6 on 2024-05-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userdailyquest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdailyquest',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDailyGoal',
        ),
        migrations.DeleteModel(
            name='UserDailyQuest',
        ),
    ]
